export const siteConfig = {
  words: [
    'apple',
    'breeze',
    'candle',
    'dolphin',
    'eclipse',
    'forest',
    'galaxy',
    'horizon',
    'island',
    'jungle',
    'kitten',
    'lantern',
    'mountain',
    'nectar',
    'ocean',
    'pyramid',
    'quartz',
    'rainbow',
    'sunrise',
    'tornado',
    'umbrella',
    'violet',
    'whisper',
    'xylophone',
    'yogurt',
    'zephyr',
  ],
  categories: {
    animals: [
      'Elephant',
      'Tiger',
      'Lion',
      'Zebra',
      'Giraffe',
      'Kangaroo',
      'Panda',
      'Koala',
      'Cheetah',
      'Leopard',
      'Wolf',
      'Fox',
      'Bear',
      'Deer',
      'Rabbit',
      'Squirrel',
      'Hedgehog',
      'Raccoon',
      'Otter',
      'Moose',
      'Beaver',
      'Skunk',
      'Opossum',
      'Armadillo',
      'Badger',
      'Camel',
      'Llama',
      'Horse',
      'Donkey',
      'Goat',
      'Sheep',
      'Cow',
      'Pig',
      'Dog',
      'Cat',
      'Hamster',
      'Guinea Pig',
      'Parrot',
      'Eagle',
      'Hawk',
      'Owl',
      'Penguin',
      'Dolphin',
      'Whale',
      'Shark',
      'Octopus',
      'Jellyfish',
      'Sea Turtle',
      'Frog',
      'Crocodile',
      'Snake',
      'Lizard',
    ],
    countries: [
      'USA',
      'Canada',
      'Mexico',
      'Brazil',
      'Argentina',
      'Ukraine',
      'France',
      'Germany',
      'Italy',
      'Spain',
      'China',
      'Japan',
      'South Korea',
      'India',
      'Russia',
      'Australia',
      'New Zealand',
      'South Africa',
      'Egypt',
      'Morocco',
      'Turkey',
      'Israel',
      'Iran',
      'Pakistan',
      'Bangladesh',
      'Indonesia',
      'Vietnam',
      'Thailand',
      'Philippines',
      'Malaysia',
      'Singapore',
      'Hong Kong',
      'Taiwan',
      'Kenya',
      'Nigeria',
      'Ethiopia',
      'Ghana',
      'Tanzania',
      'Venezuela',
      'Colombia',
      'Chile',
      'Peru',
      'Ecuador',
      'Cuba',
      'Jamaica',
      'Haiti',
      'Panama',
      'Guatemala',
    ],
    cities: [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas',
      'San Jose',
      'London',
      'Paris',
      'Berlin',
      'Madrid',
      'Rome',
      'Tokyo',
      'Beijing',
      'Shanghai',
      'Seoul',
      'Bangkok',
      'Sydney',
      'Melbourne',
      'Toronto',
      'Vancouver',
      'Montreal',
      'Dubai',
      'Istanbul',
      'Plovdiv',
      'Mumbai',
      'Delhi',
      'Bangalore',
      'Singapore',
      'Hong Kong',
      'Cape Town',
      'Johannesburg',
      'Buenos Aires',
      'Santiago',
      'Rio de Janeiro',
      'Sao Paulo',
      'Mexico',
      'Lima',
      'Bogota',
      'Caracas',
      'Cairo',
      'Casablanca',
      'Nairobi',
      'Kyiv',
      'Sofia',
      'Baghdad',
    ],
    bands: [
      'The Beatles',
      'Queen',
      'Led Zeppelin',
      'Pink Floyd',
      'Dream Theater',
      'Nirvana',
      'Metallica',
      'U2',
      'Radiohead',
      'The Eagles',
      'The Who',
      'Coldplay',
      'Green Day',
      'Linkin Park',
      'Imagine Dragons',
      'ACDC',
      'Tool',
      'Foo Fighters',
      'Guns N Roses',
      'Aerosmith',
      'Pearl Jam',
      'Mastodon',
      'Opeth',
      'Death',
      'Helloween',
      'Bon Jovi',
      'Oasis',
      'Kreator',
      'OneRepublic',
      'Megadeth',
      'Bathory',
      'The Police',
      'Black Sabbath',
      'Deep Purple',
      'Kiss',
      'The Doors',
      'The Cure',
      'Motorhead',
      'Amorphis',
      'Pantera',
      'Rammstein',
      'Nightwish',
      'Muse',
      'In Flames',
      'Korn',
      'Dio',
      'Slayer',
      'Evanescence',
      'Behemoth',
    ],
  },
  alphabet: [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
  ],
}
