export const siteConfig = {
  categories: {
    animals: [
      'Elephant',
      'Tiger',
      'Lion',
      'Zebra',
      'Giraffe',
      'Kangaroo',
      'Panda',
      'Koala',
      'Cheetah',
      'Leopard',
      'Wolf',
      'Fox',
      'Bear',
      'Deer',
      'Rabbit',
      'Squirrel',
      'Hedgehog',
      'Raccoon',
      'Otter',
      'Moose',
      'Beaver',
      'Skunk',
      'Opossum',
      'Armadillo',
      'Badger',
      'Camel',
      'Llama',
      'Horse',
      'Donkey',
      'Goat',
      'Sheep',
      'Cow',
      'Pig',
      'Dog',
      'Cat',
      'Hamster',
      'Guinea Pig',
      'Parrot',
      'Eagle',
      'Hawk',
      'Owl',
      'Penguin',
      'Dolphin',
      'Whale',
      'Shark',
      'Octopus',
      'Jellyfish',
      'Sea Turtle',
      'Frog',
      'Crocodile',
      'Snake',
      'Lizard',
    ],
    countries: [
      'USA',
      'Canada',
      'Mexico',
      'Brazil',
      'Argentina',
      'Ukraine',
      'France',
      'Germany',
      'Italy',
      'Spain',
      'China',
      'Japan',
      'South Korea',
      'India',
      'Russia',
      'Australia',
      'New Zealand',
      'South Africa',
      'Egypt',
      'Morocco',
      'Turkey',
      'Israel',
      'Iran',
      'Pakistan',
      'Bangladesh',
      'Indonesia',
      'Vietnam',
      'Thailand',
      'Philippines',
      'Malaysia',
      'Singapore',
      'Hong Kong',
      'Taiwan',
      'Kenya',
      'Nigeria',
      'Ethiopia',
      'Ghana',
      'Tanzania',
      'Venezuela',
      'Colombia',
      'Chile',
      'Peru',
      'Ecuador',
      'Cuba',
      'Jamaica',
      'Haiti',
      'Panama',
      'Guatemala',
    ],
    cities: [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas',
      'San Jose',
      'London',
      'Paris',
      'Berlin',
      'Madrid',
      'Rome',
      'Tokyo',
      'Beijing',
      'Shanghai',
      'Seoul',
      'Bangkok',
      'Sydney',
      'Melbourne',
      'Toronto',
      'Vancouver',
      'Montreal',
      'Dubai',
      'Istanbul',
      'Plovdiv',
      'Mumbai',
      'Delhi',
      'Bangalore',
      'Singapore',
      'Hong Kong',
      'Cape Town',
      'Johannesburg',
      'Buenos Aires',
      'Santiago',
      'Rio de Janeiro',
      'Sao Paulo',
      'Mexico',
      'Lima',
      'Bogota',
      'Caracas',
      'Cairo',
      'Casablanca',
      'Nairobi',
      'Kyiv',
      'Sofia',
      'Baghdad',
    ],
    bands: [
      'Beatles',
      'Queen',
      'Led Zeppelin',
      'Pink Floyd',
      'Dream Theater',
      'Nirvana',
      'Metallica',
      'U2',
      'Radiohead',
      'Eagles',
      'Who',
      'Coldplay',
      'Green Day',
      'Linkin Park',
      'Imagine Dragons',
      'ACDC',
      'Tool',
      'Foo Fighters',
      'Guns N Roses',
      'Aerosmith',
      'Pearl Jam',
      'Mastodon',
      'Opeth',
      'Death',
      'Helloween',
      'Bon Jovi',
      'Oasis',
      'Kreator',
      'OneRepublic',
      'Megadeth',
      'Bathory',
      'Police',
      'Black Sabbath',
      'Deep Purple',
      'Kiss',
      'Doors',
      'Cure',
      'Motorhead',
      'Amorphis',
      'Pantera',
      'Rammstein',
      'Nightwish',
      'Muse',
      'In Flames',
      'Korn',
      'Dio',
      'Slayer',
      'Evanescence',
      'Behemoth',
    ],
    games: [
      'Minecraft',
      'Fortnite',
      'Witcher',
      'Cyberpunk',
      'Among Us',
      'Elden Ring',
      'League of Legends',
      'World of Warcraft',
      'Call of Duty',
      'Counter Strike',
      'Valorant',
      'Overwatch',
      'GTA',
      'Zelda',
      'Super Mario',
      'Hollow Knight',
      'Dark Souls',
      'Bloodborne',
      'God of War',
      'Diablo',
      'Skyrim',
      'Battlefield',
      'Doom',
      'Metal Gear Solid',
      'Half Life',
      'Portal',
      'Starfield',
      'Mass Effect',
      'Dragon Age',
      'Destiny',
      'Genshin Impact',
      'Tomb Raider',
      'Halo',
      'FIFA',
      'NBA',
      'Sims',
      'Civilization',
      'Dota',
      'Dead Space',
    ],
    movies: [
      'Godfather',
      'Dark Knight',
      'Inception',
      'Interstellar',
      'Pulp Fiction',
      'Forrest Gump',
      'Fight Club',
      'Matrix',
      'Avengers',
      'Titanic',
      'Lion King',
      'Jurassic Park',
      'Star Wars',
      'Parasite',
      'Harry Potter',
      'Spiderman',
      'Black Panther',
      'Avengers',
      'Iron Man',
      'Frozen',
      'Moana',
      'Toy Story',
      'Incredibles',
      'Coco',
      'Batman',
      'Joker',
      'Shrek',
      'Mad Max',
      'Goodfellas',
      'Departed',
      'Kill Bill',
      'Hateful Eight',
      'Gladiator',
      'Deadpool',
      'Prestige',
      'Dune',
      'Avatar',
    ],
    colors: [
      'Red',
      'Blue',
      'Green',
      'Yellow',
      'Orange',
      'Purple',
      'Pink',
      'Brown',
      'Black',
      'White',
      'Gray',
      'Cyan',
      'Magenta',
      'Beige',
      'Navy',
      'Teal',
      'Gold',
      'Silver',
      'Crimson',
      'Amber',
      'Emerald',
      'Indigo',
      'Lilac',
      'Peach',
      'Mint',
      'Bronze',
      'Charcoal',
      'Coral',
      'Aqua',
      'Khaki',
      'Olive',
      'Ruby',
      'Salmon',
      'Plum',
      'Mustard',
      'Slate',
      'Cobalt',
      'Copper',
    ],
    fruits: [
      'Apple',
      'Banana',
      'Orange',
      'Strawberry',
      'Mango',
      'Pineapple',
      'Blueberry',
      'Raspberry',
      'Blackberry',
      'Grapes',
      'Peach',
      'Pear',
      'Plum',
      'Cherry',
      'Watermelon',
      'Kiwi',
      'Papaya',
      'Lemon',
      'Lime',
      'Coconut',
      'Apricot',
      'Tangerine',
      'Clementine',
      'Cranberry',
      'Avocado',
      'Gooseberry',
      'Nectarine',
      'Mandarin',
    ],
  },
  alphabet: [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
  ],
}
