export const siteConfig = {
  words: [
    'apple',
    'breeze',
    'candle',
    'dolphin',
    'eclipse',
    'forest',
    'galaxy',
    'horizon',
    'island',
    'jungle',
    'kitten',
    'lantern',
    'mountain',
    'nectar',
    'ocean',
    'pyramid',
    'quartz',
    'rainbow',
    'sunrise',
    'tornado',
    'umbrella',
    'violet',
    'whisper',
    'xylophone',
    'yogurt',
    'zephyr',
  ],
  categories: {
    animals: [
      'Elephant',
      'Tiger',
      'Lion',
      'Zebra',
      'Giraffe',
      'Kangaroo',
      'Panda',
      'Koala',
      'Cheetah',
      'Leopard',
      'Wolf',
      'Fox',
      'Bear',
      'Deer',
      'Rabbit',
      'Squirrel',
      'Hedgehog',
      'Raccoon',
      'Otter',
      'Moose',
      'Beaver',
      'Skunk',
      'Opossum',
      'Armadillo',
      'Badger',
      'Camel',
      'Llama',
      'Horse',
      'Donkey',
      'Goat',
      'Sheep',
      'Cow',
      'Pig',
      'Dog',
      'Cat',
      'Hamster',
      'Guinea Pig',
      'Parrot',
      'Eagle',
      'Hawk',
      'Owl',
      'Penguin',
      'Dolphin',
      'Whale',
      'Shark',
      'Octopus',
      'Jellyfish',
      'Sea Turtle',
      'Frog',
      'Crocodile',
      'Snake',
      'Lizard',
    ],
    countries: [
      'United States',
      'Canada',
      'Mexico',
      'Brazil',
      'Argentina',
      'United Kingdom',
      'France',
      'Germany',
      'Italy',
      'Spain',
      'China',
      'Japan',
      'South Korea',
      'India',
      'Russia',
      'Australia',
      'New Zealand',
      'South Africa',
      'Egypt',
      'Morocco',
      'Turkey',
      'Saudi Arabia',
      'United Arab Emirates',
      'Israel',
      'Iran',
      'Pakistan',
      'Bangladesh',
      'Indonesia',
      'Vietnam',
      'Thailand',
      'Philippines',
      'Malaysia',
      'Singapore',
      'Hong Kong',
      'Taiwan',
      'Kenya',
      'Nigeria',
      'Ethiopia',
      'Ghana',
      'Tanzania',
      'Venezuela',
      'Colombia',
      'Chile',
      'Peru',
      'Ecuador',
      'Cuba',
      'Jamaica',
      'Haiti',
      'Panama',
      'Guatemala',
    ],
    cities: [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas',
      'San Jose',
      'London',
      'Paris',
      'Berlin',
      'Madrid',
      'Rome',
      'Tokyo',
      'Beijing',
      'Shanghai',
      'Seoul',
      'Bangkok',
      'Sydney',
      'Melbourne',
      'Toronto',
      'Vancouver',
      'Montreal',
      'Dubai',
      'Istanbul',
      'Plovdiv',
      'Saint Petersburg',
      'Mumbai',
      'Delhi',
      'Bangalore',
      'Singapore',
      'Hong Kong',
      'Cape Town',
      'Johannesburg',
      'Buenos Aires',
      'Santiago',
      'Rio de Janeiro',
      'Sao Paulo',
      'Mexico',
      'Lima',
      'Bogota',
      'Caracas',
      'Cairo',
      'Casablanca',
      'Nairobi',
      'Kyiv',
      'Sofia',
      'Baghdad',
    ],
    musicBands: [
      'The Beatles',
      'Queen',
      'Led Zeppelin',
      'Pink Floyd',
      'The Rolling Stones',
      'Nirvana',
      'Metallica',
      'U2',
      'Radiohead',
      'The Eagles',
      'The Who',
      'Coldplay',
      'Green Day',
      'Linkin Park',
      'Imagine Dragons',
      'ACDC',
      'Red Hot Chili Peppers',
      'Foo Fighters',
      'Guns N Roses',
      'Aerosmith',
      'Pearl Jam',
      'The Beach Boys',
      'Fleetwood Mac',
      'The Clash',
      'The Killers',
      'Bon Jovi',
      'Oasis',
      'Arctic Monkeys',
      'OneRepublic',
      'Megadeth',
      'Maroon 5',
      'The Police',
      'Black Sabbath',
      'Deep Purple',
      'Kiss',
      'The Doors',
      'The Cure',
      'REM',
      'The Smashing Pumpkins',
      'Panic at the Disco',
      'System of a Down',
      'Paramore',
      'Muse',
      'Thirty Seconds to Mars',
      'Kings of Leon',
      'Fall Out Boy',
      'Imagine Dragons',
      'Evanescence',
      'The Chainsmokers',
      'Daft Punk',
    ],
  },
  alphabet: [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
  ],
}
